//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestThreadLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinMaxAvgThread
    {
        public int Id { get; set; }
        public Nullable<int> Minimum { get; set; }
        public Nullable<int> Maximum { get; set; }
        public Nullable<int> Average { get; set; }
        public System.DateTime LastExecution { get; set; }
        public int TaskId { get; set; }
    
        public virtual TaskList TaskList { get; set; }
    }
}
